apiVersion: apps/v1
kind: Deployment
metadata:
  name: corrdiff-nim-laurahu
  namespace: sdsu-shen-climate-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corrdiff-nim-laurahu
  template:
    metadata:
      labels:
        app: corrdiff-nim-laurahu
    spec:
      imagePullSecrets:
      - name: ngc-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-L40
      restartPolicy: Always
      containers:
      - name: corrdiff-nim
        image: nvcr.io/nim/nvidia/corrdiff:1.0.0
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: NGC_API_KEY
          value: "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"
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/gpu: "1"
          limits:
            memory: "64Gi"
            cpu: "16"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      tolerations:
      - key: nautilus.io/csu-tide
        operator: Exists
        effect: NoSchedule
      - key: nautilus.io/sdsu-fix
        operator: Exists
        effect: NoSchedule
      - key: nautilus.io/reservation
        operator: Equal
        value: csu-tide
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: corrdiff-nim-service-laurahu
  namespace: sdsu-shen-climate-lab
spec:
  selector:
    app: corrdiff-nim-laurahu
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

